---
- name: Stop if running with elevated privileges.
  fail:
    msg: >-
      WARNING! You should not compile the Linux kernel with
      superuser privileges. Doing so may create an unbootable
      system. See Greg Kroah-Hartman's Linux Kernel in a Nutshell
      for anecdotes about how doing so has broken systems
      in the past: http://www.kroah.com/lkn/
  when: ansible_env.USER == 'root'

  # Install packages before fetching dynamic URLs, since python-requests
  # is required by the URL-fetching Ansible module.
- include: packages.yml

- name: Include grsecurity download URLs.
  # Dynamically reference newest patch and kernel versions,
  # according to patch type 'test' or 'stable'.
  grsecurity_urls:
    patch_type: "{{ grsecurity_build_patch_type }}"
  # Setting task to "always" run, because other tasks will
  # without the imported vars. Usually defaults would handle ensuring
  # vars aren't missing, but we're conditionally including vars.
  tags:
    - always

- include: gpg_keys.yml

- include: fetch_linux_kernel_source.yml

- include: fetch_grsecurity_files.yml

- include: fetch_ubuntu_overlay.yml
  when: grsecurity_build_include_ubuntu_overlay == true

- include: verify.yml

- include: ccache.yml
  when: grsecurity_build_use_ccache == true

- include: prepare_source_directory.yml
  tags: prepare

- include: configure.yml
  tags: configure
  when: grsecurity_build_strategy != "manual" or
        grsecurity_build_custom_config != ''

- include: compile.yml
  tags: compile
  when: grsecurity_build_strategy != "manual" or
        grsecurity_build_custom_config != ''
