---
- name: Copy kernel deb packages to install.
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ grsecurity_install_download_dir }}/{{ item|basename }}"
  register: grsecurity_install_copy_deb_packages_result
  with_items: "{{ grsecurity_install_combined_deb_packages }}"

- name: Install PaX utilities.
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  # Always install paxtest, but allow paxctl to be skipped, in case paxctld is used.
  with_flattened:
    - ['paxtest']
    - "{{ ['paxctl'] if grsecurity_install_set_paxctl_flags else [] }}"

- name: Install grsecurity-patched kernel deb package.
  become: yes
  apt:
    deb: "{{ grsecurity_install_download_dir }}/{{ item.item | basename }}"
    # Adding --skip-same-version to avoid an interactive dpkg prompt
    # about overwriting lib modules. A subsequent task will validate
    # that a grsec-patched kernel is actually running.
    dpkg_options: skip-same-version,force-confdef,force-confold
  with_items: "{{ grsecurity_install_copy_deb_packages_result.results }}"
  when: item.changed == true or
        grsecurity_install_force_install == true
  notify:
    - Update GRUB.
    - Update host facts.

  # Force handlers to run immediately, so grub config is updated.
- meta: flush_handlers
