---
- name: Reboot into the grsecurity kernel.
  # Simply rebooting causes the subsequent wait_for task to fail. See here:
  # https://github.com/ansible/ansible/issues/10616
  # Sleeping and then shutting down, via the shell module, is a workaround.
  shell: sleep 3 && shutdown -r now "Rebooting into the grsec kernel..."
  async: 1
  poll: 0
  ignore_errors: true
  become: yes

- name: Wait for server to come back.
  local_action: wait_for
    host={{ ansible_ssh_host }}
    port={{ ansible_ssh_port | default('22')}}
    delay=30
    state=started
  become: false

  # Adding extra wait time to prevent timeouts
  # during debugging. Likely not necessary, but test
  # before removing.
- name: Wait extra time for server to come back up.
  pause:
    seconds: 30

  # Running the setup module will refresh the `ansible_kernel` host fact
  # with the current value. The `grsecurity_install_desired_kernel_version` host fact
  # persists from when it was set earlier in the role.
- name: Refresh host facts.
  action: setup

- name: Fail if grsecurity kernel not running.
  fail:
    msg: >
      Grsecurity kernel is not running. Expected to find
      {{ grsecurity_install_desired_kernel_version }}. Instead, found
      kernel {{ ansible_kernel }}.
  when: grsecurity_install_desired_kernel_version != ansible_kernel and
        grsecurity_install_reboot == true

- name: Display message about required reboot.
  debug:
    msg: >-
      Installed grsecurity-patched kernel version '{{ grsecurity_install_desired_kernel_version }}'.
      You must reboot the host to load the new kernel.
  when: grsecurity_install_desired_kernel_version != ansible_kernel and
        grsecurity_install_reboot == false
